# Generated by Django 4.0.3 on 2022-03-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
